model_name: "Qwen/Qwen2.5-3B-Instruct"
model_ama: "Qwen/Qwen2.5-Coder-0.5B-Instruct"
model_exp: "Qwen/Qwen2.5-1.5B-Instruct"
quantization: "4bit"
device: "cuda"
strategy: "top_k"  # Options: "auto", "greedy", "beam_search", "top_k", "top_p", "temperature", "contrastive"
head_parameter: 1.0
default_params:
  max_length: 1000
  temperature: 1.0
  top_k: 50
  top_p: 0.9
  num_beams: 3