model_name: "Qwen/Qwen2.5-3B-Instruct"
model_ama: "Qwen/Qwen2.5-Coder-0.5B-Instruct"  ## used for contrastive strategy, ignore otherwise
model_exp: "Qwen/Qwen2.5-1.5B-Instruct" ## used for exploratory mode, ignore otherwise
quantization: "4bit"
device: "cuda"
strategy: "top_k"  # Options: "auto", "greedy", "beam_search", "top_k", "top_p", "temperature", "contrastive"
mode: "exploratory"  # or "focused"
head_parameter: 1.0 ## this is for the contrastive strategy
default_params:
  max_length: 1000
  temperature: 1.0
  top_k: 50
  top_p: 0.9
  num_beams: 3
